language: python
python:
  - "3.4"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - python setup.py install
  - pip install coveralls
script:
  - nosetests --exe --with-coverage
after_success:
  - coveralls
